[package]
name = "classes"
version = "0.1.0"
authors = ["augustotimm <augusto.tes@gmail.com>"]

[dependencies]
rand = "0.5.5"

 [lib]
 name = "classes"
 path = "src/lib.rs"
 [[bin]]
 name = "Game"
 path = "src/bin.rs"